import type { KnowledgeCard, KnowledgeKind, KnowledgeVolatility } from './marketing'

type Mechanism = NonNullable<KnowledgeCard['mechanism']>

type Seed = {
  id: string
  title: [ru: string, en: string]
  summary: [ru: string, en: string]
  guidance: [ru: string, en: string]
  tags: string[]
  pages: string
  routes?: string[]
  kind?: KnowledgeKind
  mechanism?: Mechanism
  volatility?: KnowledgeVolatility
  confidence?: KnowledgeCard['confidence']
}

const card = (seed: Seed): KnowledgeCard => ({
  id: seed.id,
  kind: seed.kind ?? 'principle',
  title: { ru: seed.title[0], en: seed.title[1] },
  summary: { ru: seed.summary[0], en: seed.summary[1] },
  guidance: { ru: seed.guidance[0], en: seed.guidance[1] },
  tags: seed.tags,
  routes: seed.routes,
  mechanism: seed.mechanism,
  source: 'SteamИздат, «Библия маркетинга игр», редакция 2025',
  sourcePages: seed.pages,
  sourceYear: 2025,
  showSource: false,
  volatility: seed.volatility ?? 'medium',
  confidence: seed.confidence ?? 'curated',
})

/**
 * Compact, paraphrased decision cards extracted from the private SteamИздат
 * handbook. They contain no links or long excerpts and are retrieved locally
 * before Claude inference. Source metadata is retained for maintainability but
 * deliberately hidden from MarCat's user-facing answers.
 */
export const STEAMIZDAT_KNOWLEDGE_CARDS: KnowledgeCard[] = [
  card({
    id: 'marketing-market-fit',
    title: ['Сначала проверьте рынок и аудиторию', 'Validate the market and audience first'],
    summary: [
      'Жанр, сеттинг, похожие игры и ожидания игроков определяют не только продукт, но и стоимость его продвижения.',
      'Genre, setting, comparable games and player expectations shape both the product and its acquisition cost.',
    ],
    guidance: [
      'До масштабирования производства соберите 8–12 сопоставимых игр, сравните спрос, отзывы, цены и маркетинговые ходы, затем сформулируйте одну проверяемую причину выбрать вашу игру.',
      'Before scaling production, collect 8–12 comparable games, compare demand, reviews, prices and campaigns, then state one testable reason to choose your game.',
    ],
    tags: ['рынок', 'аудитория', 'жанр', 'сеттинг', 'конкуренты', 'market', 'audience', 'genre', 'positioning'],
    pages: '4–7',
    routes: ['/g/', '/analytics'],
    mechanism: 'traffic',
  }),
  card({
    id: 'marketing-start-window',
    title: ['Открывайте страницу задолго до релиза', 'Open the store page well before release'],
    summary: [
      'Страница Steam нужна не в финале разработки, а когда уже можно ясно показать игру и начать накапливать аудиторию.',
      'A Steam page is useful before the end of development, once the game can be explained clearly and audience building can begin.',
    ],
    guidance: [
      'Планируйте страницу и первые сильные материалы примерно за 6–12 месяцев до релиза; если качества ещё нет, сначала закройте позиционирование, капсулу и демонстрируемый геймплей.',
      'Plan the page and first strong assets roughly 6–12 months before release; if quality is not ready, fix positioning, capsule and demonstrable gameplay first.',
    ],
    tags: ['старт', 'страница', 'релиз', 'тайминг', 'steam', 'store page', 'release', 'timing'],
    pages: '6',
    routes: ['/g/', '/calendar'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'launch-sequence',
    kind: 'heuristic',
    title: ['Кампания строится этапами', 'Build the campaign in stages'],
    summary: [
      'Позиционирование, анонс, плейтест, демо, фестиваль и релиз должны последовательно снимать риски и усиливать следующий этап.',
      'Positioning, announcement, playtest, demo, festival and release should remove risk in sequence and strengthen the next stage.',
    ],
    guidance: [
      'Создайте крупные вехи как дедлайны, свяжите с ними только нужные задачи и оставьте между вехами небольшие новости: обновления, клипы, девлоги и результаты тестов.',
      'Create major milestones as deadlines, attach only necessary tasks, and keep smaller beats between them: updates, clips, devlogs and test findings.',
    ],
    tags: ['кампания', 'анонс', 'плейтест', 'демо', 'фестиваль', 'релиз', 'campaign', 'launch', 'milestones'],
    pages: '6–8',
    routes: ['/g/', '/tasks', '/calendar'],
    mechanism: 'traffic',
  }),
  card({
    id: 'marketing-budget-scenarios',
    kind: 'heuristic',
    title: ['Бюджет зависит от продаваемости жанра', 'Budget depends on genre marketability'],
    summary: [
      'Лёгкая разработка не означает дешёвый маркетинг: привычный аудитории жанр может продвигаться проще, чем визуально слабый массовый жанр.',
      'Easy development does not imply cheap marketing: a genre with clear demand can be easier to market than a visually weak mass-market genre.',
    ],
    guidance: [
      'Составьте три сценария — минимальный, рабочий и усиленный — и привяжите расходы к проверкам: капсула, демо, creator outreach и платный трафик. Не масштабируйте канал до подтверждённой конверсии.',
      'Create minimum, working and accelerated scenarios tied to tests: capsule, demo, creator outreach and paid traffic. Do not scale a channel before conversion is demonstrated.',
    ],
    tags: ['бюджет', 'жанр', 'окупаемость', 'сценарий', 'budget', 'genre', 'roi', 'scenario'],
    pages: '6',
    routes: ['/analytics', '/g/'],
    mechanism: 'traffic',
    confidence: 'heuristic',
  }),
  card({
    id: 'steam-page-quality',
    title: ['Страница Steam должна объяснять игру мгновенно', 'The Steam page must explain the game instantly'],
    summary: [
      'Позиционирование, капсула, первые секунды трейлера и первые скриншоты должны быстро передавать жанр, фантазию игрока и главное отличие.',
      'Positioning, capsule, trailer opening and first screenshots should quickly communicate genre, player fantasy and the main differentiator.',
    ],
    guidance: [
      'Покажите страницу человеку без контекста на пять секунд и спросите: что это за игра, что в ней делают и чем она интересна. Исправляйте первый непонятный элемент, а не весь лендинг сразу.',
      'Show the page to someone without context for five seconds and ask what the game is, what players do and why it is interesting. Fix the first unclear element, not the entire page at once.',
    ],
    tags: ['steam', 'страница', 'позиционирование', 'конверсия', 'store', 'page', 'positioning', 'conversion'],
    pages: '8–11',
    routes: ['/g/', '/analytics'],
    mechanism: 'store_conversion',
  }),
  card({
    id: 'steam-capsule-signal',
    title: ['Капсула сначала сообщает жанр', 'The capsule signals genre first'],
    summary: [
      'Хорошая капсула узнаваема для аудитории жанра, но содержит один собственный визуальный крючок.',
      'A good capsule is recognizable to the genre audience while carrying one distinctive visual hook.',
    ],
    guidance: [
      'Соберите капсулы успешных прямых конкурентов, отметьте повторяющиеся сигналы жанра и сделайте 3 варианта со своим героем, конфликтом или настроением. Проверяйте в малом размере рядом с конкурентами.',
      'Collect capsules from successful direct competitors, mark recurring genre cues, and create three variants around your character, conflict or mood. Test at small size beside competitors.',
    ],
    tags: ['капсула', 'арт', 'жанр', 'конкуренты', 'capsule', 'key art', 'genre', 'ab test'],
    pages: '8, 11, 21',
    routes: ['/g/', '/analytics'],
    mechanism: 'store_conversion',
  }),
  card({
    id: 'steam-screenshot-story',
    title: ['Скриншоты рассказывают историю механик', 'Screenshots tell a mechanics story'],
    summary: [
      'Первые изображения должны показать жанр и действие, а вся лента — разнообразие механик, прогрессии, мест и состояний.',
      'The first images should show genre and action, while the full strip demonstrates mechanics, progression, locations and states.',
    ],
    guidance: [
      'Начните с сильного кадра и чистого геймплея, затем покажите прогрессию или интерфейс и альтернативные механики. Проверьте миниатюры: соседние кадры не должны выглядеть одинаково.',
      'Start with a strong image and clear gameplay, then show progression or UI and alternate mechanics. Check thumbnails: adjacent frames should not look interchangeable.',
    ],
    tags: ['скриншоты', 'механики', 'геймплей', 'миниатюры', 'screenshots', 'gameplay', 'mechanics', 'thumbnails'],
    pages: '9, 11',
    routes: ['/g/'],
    mechanism: 'store_conversion',
    volatility: 'low',
  }),
  card({
    id: 'steam-trailer-hook',
    title: ['Трейлер начинается с доказательства', 'Open the trailer with proof'],
    summary: [
      'Зритель должен увидеть сильный игровой момент до логотипа, предыстории и длинного разгона.',
      'The viewer should see a strong playable moment before logos, lore or a long setup.',
    ],
    guidance: [
      'Поставьте лучший понятный момент в первые 3–5 секунд, меняйте тему или кадр каждые несколько секунд и проверяйте, что трейлер показывает реальный геймплей и заканчивается одним CTA.',
      'Put the clearest strong moment in the first 3–5 seconds, change theme or shot every few seconds, show real gameplay, and end with one CTA.',
    ],
    tags: ['трейлер', 'хук', 'геймплей', 'cta', 'trailer', 'hook', 'gameplay', 'video'],
    pages: '8–9, 76–80',
    routes: ['/g/'],
    mechanism: 'store_conversion',
  }),
  card({
    id: 'steam-about-section',
    title: ['Главное размещайте до раскрытия описания', 'Put the essentials above the fold'],
    summary: [
      'Большинство посетителей бегло просматривает начало описания, поэтому первые гифки и особенности несут основную нагрузку.',
      'Most visitors skim the opening of the description, so the first GIFs and features carry most of the burden.',
    ],
    guidance: [
      'Сделайте первую гифку видимой без дополнительного клика. Для каждой из 4–5 главных особенностей используйте короткий заголовок, демонстрацию и одно объясняющее предложение.',
      'Keep the first GIF visible without another click. For each of 4–5 main features, use a short heading, a demonstration and one explanatory sentence.',
    ],
    tags: ['описание', 'гифки', 'фичи', 'about', 'description', 'gifs', 'features', 'steam'],
    pages: '8–9',
    routes: ['/g/'],
    mechanism: 'store_conversion',
    volatility: 'low',
  }),
  card({
    id: 'steam-tags-recommendations',
    title: ['Теги формируют соседство игры', 'Tags shape the game’s neighborhood'],
    summary: [
      'Первые конкретные жанровые теги помогают Steam понять, с какими играми и игроками сопоставлять проект.',
      'The first specific genre tags help Steam decide which games and players your project belongs beside.',
    ],
    guidance: [
      'Сравните первые теги у прямых конкурентов, уберите слишком общие ярлыки из начала списка и проверьте, какие похожие игры и рекомендации получаются после изменения.',
      'Compare the leading tags of direct competitors, move overly broad labels out of the first positions, and inspect the similar games and recommendations after changes.',
    ],
    tags: ['теги', 'рекомендации', 'похожие игры', 'steam', 'tags', 'recommendations', 'similar games'],
    pages: '9–10, 13, 21, 26',
    routes: ['/g/'],
    mechanism: 'store_conversion',
    volatility: 'high',
  }),
  card({
    id: 'steam-localization-readiness',
    kind: 'platform_rule',
    title: ['Локализация влияет на региональную видимость', 'Localization affects regional visibility'],
    summary: [
      'Страница, демо и поддерживаемые языки должны быть согласованы до крупных фестивалей и релиза.',
      'Store page, demo and supported languages should be aligned before major festivals and release.',
    ],
    guidance: [
      'Зафиксируйте целевые регионы, локализуйте страницу и ключевые материалы заранее и отдельно проверьте названия, логотипы и читаемость для CJK-языков. Актуальные требования сверяйте со Steamworks.',
      'Define target regions, localize the page and key assets early, and separately verify names, logos and readability for CJK languages. Check current requirements in Steamworks.',
    ],
    tags: ['локализация', 'языки', 'регионы', 'cjk', 'localization', 'languages', 'regions', 'steamworks'],
    pages: '10, 15, 21',
    routes: ['/g/', '/festivals'],
    mechanism: 'store_conversion',
    volatility: 'high',
  }),
  card({
    id: 'steam-announcement-pack',
    title: ['Анонс — синхронный пакет, а не один пост', 'An announcement is a synchronized package'],
    summary: [
      'Страница, трейлер, тексты, список контактов и публикации должны выйти вместе и направлять на одно действие.',
      'Store page, trailer, copy, contact list and posts should launch together and point to one action.',
    ],
    guidance: [
      'До даты анонса подготовьте страницу, трейлер, короткий и длинный питч, медиа-лист и посты. В день запуска измеряйте визиты и вишлисты по каналам, а через 48–72 часа решите, что повторять.',
      'Before announcement day, prepare the page, trailer, short and long pitch, media list and posts. Measure visits and wishlists by channel, then decide what to repeat after 48–72 hours.',
    ],
    tags: ['анонс', 'пресс', 'трейлер', 'рассылка', 'announcement', 'press', 'trailer', 'outreach'],
    pages: '10–11',
    routes: ['/tasks', '/calendar', '/creators'],
    mechanism: 'traffic',
  }),
  card({
    id: 'steam-developer-page',
    title: ['Страница разработчика накапливает аудиторию портфеля', 'A developer page compounds portfolio audience'],
    summary: [
      'Подписчики страницы студии получают новости о новых играх, демо и релизах, а не только об одном продукте.',
      'Followers of the studio page can receive news about new games, demos and releases rather than a single product.',
    ],
    guidance: [
      'Создайте страницу разработчика или издателя, свяжите все релевантные продукты и поддерживайте единое оформление. Это особенно полезно, если планируется несколько игр или DLC.',
      'Create a developer or publisher page, connect all relevant products and maintain consistent presentation. This matters most when multiple games or DLC are planned.',
    ],
    tags: ['разработчик', 'издатель', 'портфель', 'подписчики', 'developer page', 'publisher', 'portfolio'],
    pages: '12',
    routes: ['/g/'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'festival-selection',
    title: ['Фестиваль должен совпадать с аудиторией и готовностью', 'Festival fit requires audience and readiness'],
    summary: [
      'Бесплатное участие полезно, если аудитория релевантна, страница готова и команда способна поддержать событие.',
      'Free participation is useful when the audience fits, the page is ready and the team can support the event.',
    ],
    guidance: [
      'Оценивайте каждый фестиваль по аудитории, дедлайну, требуемому билду, Steam-витрине и плану коммуникации. Не ставьте в календарь событие без владельца и следующего действия.',
      'Evaluate each festival by audience, deadline, required build, Steam presence and communication plan. Do not add an event without an owner and next action.',
    ],
    tags: ['фестиваль', 'аудитория', 'дедлайн', 'готовность', 'festival', 'audience', 'deadline', 'readiness'],
    pages: '12–13',
    routes: ['/festivals', '/calendar'],
    mechanism: 'festival_readiness',
  }),
  card({
    id: 'next-fest-readiness',
    kind: 'platform_rule',
    title: ['Next Fest усиливает уже готовую демо', 'Next Fest amplifies an already ready demo'],
    summary: [
      'Фестиваль плохо заменяет тестирование: сильнее выступают понятные страницы и демо с подтверждённым удержанием.',
      'The festival is a poor substitute for testing: clear pages and demos with demonstrated engagement perform better.',
    ],
    guidance: [
      'До подачи проверьте актуальные правила Steamworks. Затем закройте плейтест, критические проблемы демо, локализацию, страницу, трейлер и рассылки до, в день и после фестиваля.',
      'Verify current Steamworks rules before applying. Then complete playtesting, critical demo fixes, localization, page, trailer and outreach before, during and after the festival.',
    ],
    tags: ['next fest', 'фестиваль', 'демо', 'плейтест', 'steam', 'festival', 'demo', 'readiness'],
    pages: '12–15',
    routes: ['/festivals', '/calendar', '/tasks'],
    mechanism: 'festival_readiness',
    volatility: 'high',
  }),
  card({
    id: 'demo-launch-plan',
    title: ['Запуск демо — отдельная кампания', 'Treat the demo launch as its own campaign'],
    summary: [
      'Демо приносит пользу, когда билд, страница, creator preview, уведомление и фестиваль синхронизированы.',
      'A demo is most useful when build, page, creator preview, notification and festival timing are synchronized.',
    ],
    guidance: [
      'Определите дату, заранее выдайте проверенный билд выбранным авторам, подготовьте трейлер и пресс-пакет, а публичный запуск свяжите с одним сильным инфоповодом. Правила уведомлений проверяйте в Steamworks.',
      'Set a date, provide a validated build to selected creators early, prepare a trailer and press pack, and connect public launch to one strong moment. Verify notification rules in Steamworks.',
    ],
    tags: ['демо', 'запуск', 'ключи', 'инфлюенсеры', 'demo', 'launch', 'keys', 'creators'],
    pages: '14–15',
    routes: ['/tasks', '/calendar', '/creators'],
    mechanism: 'festival_readiness',
  }),
  card({
    id: 'demo-retention-diagnosis',
    kind: 'heuristic',
    title: ['Демо проверяют по поведению, а не по факту публикации', 'Judge a demo by behavior, not publication'],
    summary: [
      'Медиана времени, точки выхода, завершение ключевого цикла и качественный фидбек показывают, готово ли демо к масштабированию.',
      'Median playtime, exit points, core-loop completion and qualitative feedback show whether a demo is ready to scale.',
    ],
    guidance: [
      'Инструментируйте туториал и ключевые этапы, собирайте форму при выходе и анализируйте причины оттока. Сначала исправьте крупнейший ранний провал, затем повторите тест на новой выборке.',
      'Instrument tutorial and key milestones, collect an exit survey and analyze churn reasons. Fix the largest early drop first, then repeat the test with a fresh cohort.',
    ],
    tags: ['демо', 'удержание', 'медиана', 'аналитика', 'demo', 'retention', 'playtime', 'analytics'],
    pages: '15–16',
    routes: ['/analytics', '/tasks'],
    mechanism: 'festival_readiness',
    confidence: 'heuristic',
  }),
  card({
    id: 'playtest-before-demo',
    title: ['Плейтест должен предшествовать публичному демо', 'Playtest before the public demo'],
    summary: [
      'Закрытый или управляемый тест дешевле выявляет проблемы обучения, темпа, багов и ожиданий, чем крупный публичный запуск.',
      'A controlled test finds onboarding, pacing, bug and expectation problems more cheaply than a major public launch.',
    ],
    guidance: [
      'Сформулируйте 3–5 вопросов теста, настройте сбор поведения и фидбека, привлеките релевантных игроков и не открывайте демо широкой аудитории, пока критические провалы не объяснены.',
      'Define 3–5 test questions, instrument behavior and feedback, recruit relevant players, and do not expose the demo broadly until critical failures are understood.',
    ],
    tags: ['плейтест', 'демо', 'фидбек', 'тестеры', 'playtest', 'demo', 'feedback', 'testing'],
    pages: '14–16',
    routes: ['/tasks', '/calendar'],
    mechanism: 'festival_readiness',
    volatility: 'low',
  }),
  card({
    id: 'prologue-decision',
    kind: 'heuristic',
    title: ['Пролог — отдельный продукт с отдельной ценой поддержки', 'A prologue is a separate product to support'],
    summary: [
      'Пролог может дать отзывы и дополнительную витрину, но требует собственного качества, локализации и продвижения.',
      'A prologue can generate reviews and another surface, but requires its own quality, localization and promotion.',
    ],
    guidance: [
      'Используйте пролог только если игровой цикл самодостаточен и его аудиторию можно перевести в основную игру. Сравните стоимость второй страницы и кампании с улучшением обычного демо.',
      'Use a prologue only when its loop is self-contained and its audience can be moved to the main game. Compare the cost of a second page and campaign with improving the regular demo.',
    ],
    tags: ['пролог', 'демо', 'отзывы', 'воронка', 'prologue', 'demo', 'reviews', 'funnel'],
    pages: '16–17',
    routes: ['/g/', '/tasks'],
    mechanism: 'traffic',
    confidence: 'heuristic',
  }),
  card({
    id: 'early-access-decision',
    title: ['Early Access подходит не каждой игре', 'Early Access does not fit every game'],
    summary: [
      'Ранний доступ полезен играм с повторяемым циклом, долгой разработкой и сообществом, но снижает силу момента релиза 1.0.',
      'Early Access helps games with repeatable loops, ongoing development and community input, but weakens the 1.0 launch moment.',
    ],
    guidance: [
      'Перед выбором проверьте: достаточно ли контента уже сейчас, можно ли регулярно обновлять игру, нужен ли фидбек по системам и готова ли команда публично выполнять roadmap.',
      'Before choosing it, verify that enough content exists now, updates can ship regularly, systemic feedback is valuable and the team can publicly execute a roadmap.',
    ],
    tags: ['early access', 'ранний доступ', 'roadmap', 'обновления', 'community', 'release'],
    pages: '17–18',
    routes: ['/g/', '/calendar'],
    mechanism: 'traffic',
  }),
  card({
    id: 'early-access-operations',
    title: ['Ранний доступ требует операционного ритма', 'Early Access needs an operating cadence'],
    summary: [
      'Без понятного roadmap, регулярных патчей и честной коммуникации Early Access быстро теряет доверие.',
      'Without a clear roadmap, regular patches and honest communication, Early Access quickly loses trust.',
    ],
    guidance: [
      'Опубликуйте достижимый roadmap, заведите календарь патчей и контентных обновлений, ведите известные проблемы и регулярно объясняйте, что изменилось благодаря фидбеку.',
      'Publish an achievable roadmap, schedule patches and content updates, maintain known issues and regularly explain what changed because of feedback.',
    ],
    tags: ['early access', 'roadmap', 'патчи', 'комьюнити', 'updates', 'operations', 'community'],
    pages: '17',
    routes: ['/tasks', '/calendar', '/events'],
    mechanism: 'product_workflow',
    volatility: 'low',
  }),
  card({
    id: 'press-kit-outreach-package',
    title: ['Пресс-кит сокращает путь до публикации', 'A press kit shortens the path to coverage'],
    summary: [
      'Автору нужны готовые материалы и рабочий билд, чтобы быстро понять игру и выпустить контент без дополнительной переписки.',
      'A creator needs ready assets and a working build to understand the game and publish without extra back-and-forth.',
    ],
    guidance: [
      'Соберите логотипы, key art, скриншоты, короткие клипы, B-roll, факты, контакты и ссылки. Для обзора приложите стабильный билд или ключ и персональное письмо с конкретной причиной релевантности.',
      'Package logos, key art, screenshots, short clips, B-roll, facts, contacts and links. For review, include a stable build or key and a personal note explaining the fit.',
    ],
    tags: ['пресс-кит', 'b-roll', 'ключи', 'рассылка', 'press kit', 'assets', 'keys', 'outreach'],
    pages: '18–19',
    routes: ['/creators', '/tasks'],
    mechanism: 'outreach',
    volatility: 'low',
  }),
  card({
    id: 'steam-visibility-funnel',
    kind: 'heuristic',
    title: ['Видимость Steam — несколько разных воронок', 'Steam visibility is several different funnels'],
    summary: [
      'Popular Upcoming, Discovery Queue, New & Trending, рекомендации и скидочные витрины включаются разными сигналами и решают разные задачи.',
      'Popular Upcoming, Discovery Queue, New & Trending, recommendations and discount surfaces use different signals and serve different jobs.',
    ],
    guidance: [
      'Для каждой цели запишите нужную аудиторию, входной сигнал и метрику результата. Не используйте один общий “трафик Steam”: отдельно анализируйте страницу, DQ, релизные и скидочные поверхности.',
      'For each target, record its audience, entry signal and outcome metric. Do not use one generic “Steam traffic” bucket; separate page, DQ, launch and discount surfaces.',
    ],
    tags: ['видимость', 'popular upcoming', 'discovery queue', 'new trending', 'steam', 'visibility', 'funnel'],
    pages: '19–27',
    routes: ['/analytics', '/g/'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'discovery-queue-diagnosis',
    kind: 'heuristic',
    title: ['Discovery Queue проверяет упаковку без контекста', 'Discovery Queue tests packaging without context'],
    summary: [
      'Реакция аудитории на key art, теги и обещание страницы может усиливать или сокращать дальнейшие показы.',
      'Audience response to key art, tags and page promise can increase or reduce later exposure.',
    ],
    guidance: [
      'В Steamworks выделите визиты DQ по дням после релиза и сопоставьте их с переходами, покупками и изменениями страницы. Если интерес слаб, сначала тестируйте key art и ясность жанра.',
      'In Steamworks, isolate DQ visits by day after release and compare them with visits, purchases and page changes. If interest is weak, test key art and genre clarity first.',
    ],
    tags: ['discovery queue', 'dq', 'key art', 'теги', 'steamworks', 'recommendations'],
    pages: '20–21',
    routes: ['/analytics'],
    mechanism: 'store_conversion',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'wishlist-momentum',
    kind: 'heuristic',
    title: ['Вишлисты — сигнал, а не самоцель', 'Wishlists are a signal, not the end goal'],
    summary: [
      'Количество, скорость набора, качество аудитории и конверсия страницы нужно рассматривать вместе.',
      'Total count, acquisition velocity, audience quality and page conversion should be read together.',
    ],
    guidance: [
      'Сопоставляйте изменение темпа с конкретными активностями и источниками, но формулируйте выводы как гипотезы. Влияние внешнего трафика на алгоритмы Steam считается спорным и изменчивым.',
      'Compare velocity changes with specific activities and sources, but frame conclusions as hypotheses. The effect of external traffic on Steam algorithms is disputed and volatile.',
    ],
    tags: ['вишлисты', 'wishlists', 'темп', 'velocity', 'traffic', 'conversion', 'steam'],
    pages: '23–27',
    routes: ['/analytics', '/events', '/g/'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'wishlist-experiment-design',
    title: ['Измеряйте кампании как короткие эксперименты', 'Measure campaigns as short experiments'],
    summary: [
      'Без даты, UTM, расхода и контрольного периода рост вишлистов нельзя честно связать с активностью.',
      'Without dates, UTM, spend and a baseline period, wishlist growth cannot be honestly connected to an activity.',
    ],
    guidance: [
      'Перед запуском сохраните базовый дневной темп. Для каждого канала задайте UTM, бюджет и окно оценки; после кампании сравните визиты, конверсию и изменение общего темпа, учитывая параллельные события.',
      'Record baseline daily velocity before launch. Give each channel a UTM, budget and evaluation window; compare visits, conversion and total velocity afterward while accounting for overlapping events.',
    ],
    tags: ['вишлисты', 'utm', 'эксперимент', 'бюджет', 'wishlists', 'measurement', 'campaign', 'baseline'],
    pages: '18, 23–25, 47',
    routes: ['/analytics', '/events'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'influencer-fit',
    kind: 'heuristic',
    title: ['Фит важнее размера канала', 'Fit matters more than channel size'],
    summary: [
      'Приоритет получают авторы с опытом в похожих играх, подходящим языком, активной аудиторией и свежими публикациями.',
      'Prioritize creators with similar-game experience, suitable language, active audiences and recent publishing.',
    ],
    guidance: [
      'Ищите авторов через похожие игры, проверяйте последние ролики и реальные просмотры, затем фиксируйте конкретную причину фита. Большой канал без жанрового совпадения не должен быть первым.',
      'Find creators through comparable games, inspect recent videos and real views, then record a specific fit reason. A large channel without genre fit should not be first.',
    ],
    tags: ['инфлюенсеры', 'блогеры', 'стримеры', 'фит', 'creators', 'influencers', 'streamers', 'fit'],
    pages: '28–34, 98–101',
    routes: ['/creators'],
    mechanism: 'outreach',
  }),
  card({
    id: 'influencer-outreach-sequence',
    title: ['Рассылка — управляемая последовательность', 'Outreach is a managed sequence'],
    summary: [
      'Короткий целевой список, персональное письмо, стабильный ключ и один разумный follow-up работают лучше массового неразмеченного потока.',
      'A short target list, personal pitch, stable key and one reasonable follow-up work better than an untracked blast.',
    ],
    guidance: [
      'Разбейте авторов на волны, персонализируйте первые строки, дайте однострочный питч, клип, ключ и пресс-кит. Записывайте отправку, ответ, активацию и публикацию; follow-up делайте только один раз по выбранному сроку.',
      'Split creators into waves, personalize the opening, provide a one-line pitch, clip, key and press kit. Track send, reply, activation and coverage; send one follow-up at a chosen interval.',
    ],
    tags: ['рассылка', 'письмо', 'ключ', 'follow-up', 'outreach', 'email', 'key', 'crm'],
    pages: '18–19, 28–34',
    routes: ['/creators', '/tasks'],
    mechanism: 'outreach',
    volatility: 'low',
  }),
  card({
    id: 'influencer-funnel-expectations',
    kind: 'heuristic',
    title: ['Оценивайте creator outreach как воронку', 'Treat creator outreach as a funnel'],
    summary: [
      'Запрос ключа, активация и публикация — разные этапы; провал на каждом требует своего исправления.',
      'Key request, activation and coverage are separate stages; each failure needs a different fix.',
    ],
    guidance: [
      'Если мало ответов — пересмотрите фит и тему письма; если не активируют — билд, сроки и инструкция; если не публикуют — качество опыта и follow-up. Пороговые конверсии используйте только как ориентир.',
      'If replies are low, revisit fit and subject line; if activation is low, inspect build, timing and instructions; if coverage is low, inspect experience quality and follow-up. Use benchmarks only as orientation.',
    ],
    tags: ['воронка', 'активация', 'публикация', 'конверсия', 'creator funnel', 'activation', 'coverage'],
    pages: '28–34',
    routes: ['/creators', '/analytics'],
    mechanism: 'outreach',
    confidence: 'heuristic',
  }),
  card({
    id: 'revenue-scenario-planning',
    kind: 'heuristic',
    title: ['Прогнозируйте диапазон, а не одну выручку', 'Forecast a range, not one revenue number'],
    summary: [
      'Цена, жанр, рейтинг, Early Access и конверсия вишлистов делают один “средний” прогноз ненадёжным.',
      'Price, genre, rating, Early Access and wishlist conversion make one “average” forecast unreliable.',
    ],
    guidance: [
      'Постройте pessimistic/base/upside сценарии с явными допущениями по цене, возвратам, конверсии и платформенной комиссии. Обновляйте их по своим данным, а не по чужому среднему.',
      'Build pessimistic, base and upside scenarios with explicit assumptions for price, refunds, conversion and platform fee. Update them from your own data rather than an external average.',
    ],
    tags: ['выручка', 'прогноз', 'сценарий', 'конверсия', 'revenue', 'forecast', 'scenario', 'conversion'],
    pages: '34–36',
    routes: ['/analytics'],
    mechanism: 'product_workflow',
    confidence: 'heuristic',
  }),
  card({
    id: 'refund-diagnostics',
    kind: 'heuristic',
    title: ['Возвраты — диагностический сигнал', 'Refunds are a diagnostic signal'],
    summary: [
      'Высокие возвраты могут указывать на разрыв ожиданий, слабое начало, технические проблемы, цену или жанровую специфику.',
      'High refunds can signal expectation mismatch, a weak opening, technical problems, price issues or genre effects.',
    ],
    guidance: [
      'Сегментируйте возвраты по периоду, версии, региону и источнику. Сопоставьте с отзывами и временем игры; сначала исправляйте повторяющуюся раннюю причину, а не средний процент.',
      'Segment refunds by period, build, region and source. Compare with reviews and playtime; fix the recurring early cause before optimizing the average rate.',
    ],
    tags: ['возвраты', 'refunds', 'цена', 'ожидания', 'playtime', 'diagnostics'],
    pages: '36',
    routes: ['/analytics'],
    mechanism: 'store_conversion',
    confidence: 'heuristic',
  }),
  card({
    id: 'steam-review-response',
    title: ['Отвечайте на отзывы после действия', 'Respond to reviews after action'],
    summary: [
      'Ответ разработчика полезнее, когда сообщает об исправлении или проясняет факт, а не спорит с эмоцией игрока.',
      'A developer response is most useful when it reports a fix or clarifies a fact rather than arguing with player emotion.',
    ],
    guidance: [
      'Сгруппируйте повторяющиеся жалобы, исправьте проблему и коротко сообщите об этом. Позитивные отзывы можно благодарить, но не превращайте каждый review в автоматический диалог.',
      'Group recurring complaints, fix the issue and report it briefly. Thank positive reviewers when appropriate, but do not turn every review into an automated conversation.',
    ],
    tags: ['отзывы', 'reviews', 'ответ', 'рейтинг', 'steam', 'feedback', 'reputation'],
    pages: '37',
    routes: ['/events', '/g/'],
    mechanism: 'store_conversion',
    volatility: 'medium',
  }),
  card({
    id: 'bundle-collaboration-fit',
    title: ['Бандл работает через пересечение аудиторий', 'Bundles work through audience overlap'],
    summary: [
      'Лучшие партнёры близки по масштабу, жанровому интересу и качеству, но не являются полными заменителями друг друга.',
      'The best partners are similar in scale, audience interest and quality without being direct substitutes.',
    ],
    guidance: [
      'Подберите несколько игр со сравнимой аудиторией, сформулируйте общую тему и пользу каждой стороне, затем согласуйте скидку, сроки, коммуникацию и измерение переходов.',
      'Select a few games with comparable audiences, define a shared theme and value for each side, then agree on discount, timing, communication and measurement.',
    ],
    tags: ['бандл', 'коллаборация', 'аудитория', 'скидка', 'bundle', 'collaboration', 'audience', 'discount'],
    pages: '37–38',
    routes: ['/tasks', '/calendar'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'launch-date-risk',
    kind: 'heuristic',
    title: ['Дата релиза — управление конкуренцией', 'Release timing manages competition'],
    summary: [
      'Важнее универсального “лучшего дня” — не столкнуться с крупной распродажей, шумным релизом и неподготовленной командой.',
      'Avoiding a major sale, dominant release and an unprepared team matters more than a universal “best day.”',
    ],
    guidance: [
      'Проверьте календарь Steam и прямых конкурентов, оставьте буфер вокруг крупных распродаж и выберите момент, когда команда сможет поддерживать страницу, сообщество и срочные исправления несколько дней подряд.',
      'Check Steam and competitor calendars, leave a buffer around major sales, and choose a time when the team can support the page, community and urgent fixes for several days.',
    ],
    tags: ['дата релиза', 'конкуренты', 'распродажа', 'release date', 'competition', 'sale', 'calendar'],
    pages: '38–40',
    routes: ['/calendar', '/festivals'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'discount-event-strategy',
    kind: 'platform_rule',
    title: ['Скидка должна создавать событие', 'A discount should create an event'],
    summary: [
      'Скидка сильнее, когда связана с обновлением, фестивалем, DLC или другим объяснимым поводом и поддержана коммуникацией.',
      'A discount is stronger when tied to an update, festival, DLC or another explainable event and supported by communication.',
    ],
    guidance: [
      'Планируйте скидку вместе с новостью, обновлёнными ассетами и измерением продаж. Не увеличивайте глубину автоматически, если базовые продажи устойчивы; актуальные cooldown и правила проверяйте в Steamworks.',
      'Plan the discount with a news post, refreshed assets and sales measurement. Do not deepen it automatically while baseline sales are healthy; verify current cooldowns and rules in Steamworks.',
    ],
    tags: ['скидка', 'распродажа', 'discount', 'sale', 'steamworks', 'event', 'visibility'],
    pages: '40',
    routes: ['/calendar', '/events'],
    mechanism: 'traffic',
    volatility: 'high',
  }),
  card({
    id: 'dlc-visibility-plan',
    title: ['DLC требует собственного инфоповода', 'DLC needs its own communication moment'],
    summary: [
      'Новый контент может вернуть существующих игроков и создать витринный повод, если заранее подготовлены ассеты и коммуникация.',
      'New content can reactivate existing players and create a storefront moment when assets and communication are prepared.',
    ],
    guidance: [
      'Свяжите DLC с новостью, обновлением страницы, creator outreach и подходящей скидкой. Для доступных Steam-инструментов видимости и уведомлений проверьте текущие условия в Steamworks.',
      'Connect DLC to a news post, page refresh, creator outreach and an appropriate discount. Verify current Steam visibility and notification options in Steamworks.',
    ],
    tags: ['dlc', 'обновление', 'видимость', 'скидка', 'update', 'visibility', 'discount'],
    pages: '40',
    routes: ['/tasks', '/calendar', '/events'],
    mechanism: 'traffic',
    volatility: 'high',
  }),
  card({
    id: 'regional-pricing-review',
    title: ['Региональные цены требуют ручной проверки', 'Regional prices need manual review'],
    summary: [
      'Автоматическая сетка может плохо отражать покупательную способность и конкурентное окружение конкретного региона.',
      'An automatic grid may poorly reflect purchasing power and competitive context in a specific region.',
    ],
    guidance: [
      'Сравните цену с похожими играми по ключевым регионам, проверьте налоги и курс, затем отслеживайте продажи и возвраты после изменений. Избегайте резких движений без регионального контекста.',
      'Compare price with similar games in key regions, check tax and exchange context, then monitor sales and refunds after changes. Avoid sharp moves without regional context.',
    ],
    tags: ['цена', 'регионы', 'региональные цены', 'pricing', 'regions', 'regional pricing'],
    pages: '41',
    routes: ['/analytics', '/g/'],
    mechanism: 'store_conversion',
    volatility: 'high',
  }),
  card({
    id: 'itch-demo-validation',
    title: ['Itch.io можно использовать как раннюю лабораторию', 'Use Itch.io as an early validation lab'],
    summary: [
      'Браузерный или ранний билд может дать дешёвую проверку понимания и фидбека до крупного запуска в Steam.',
      'A browser or early build can cheaply test comprehension and feedback before a major Steam launch.',
    ],
    guidance: [
      'Опубликуйте ограниченный билд с конкретными вопросами, соберите отзывы и поведение, исправьте главную проблему и только затем используйте результат в Steam-демо и outreach.',
      'Publish a limited build with specific questions, collect feedback and behavior, fix the main issue, then carry the result into the Steam demo and outreach.',
    ],
    tags: ['itch.io', 'демо', 'валидация', 'браузер', 'demo', 'validation', 'playtest'],
    pages: '41',
    routes: ['/tasks', '/events'],
    mechanism: 'festival_readiness',
    volatility: 'medium',
  }),
  card({
    id: 'platform-expansion-gate',
    title: [
      'Новая платформа должна окупать операционную сложность',
      'A new platform must justify operational complexity',
    ],
    summary: [
      'Порт, сертификация, поддержка, локализация и отдельный маркетинг могут стоить больше дополнительной выручки.',
      'Porting, certification, support, localization and separate marketing can cost more than incremental revenue.',
    ],
    guidance: [
      'Для каждой платформы оцените достижимую аудиторию, стоимость порта и поддержки, доступ к витринам и синхронизацию релиза. Расширяйтесь после доказанного спроса или при сильном платформенном партнёре.',
      'For each platform, estimate reachable audience, port and support cost, storefront access and release coordination. Expand after proven demand or with a strong platform partner.',
    ],
    tags: ['платформы', 'порт', 'консоли', 'egs', 'gog', 'platforms', 'port', 'console'],
    pages: '41–42',
    routes: ['/g/'],
    mechanism: 'product_workflow',
    volatility: 'medium',
  }),
  card({
    id: 'social-content-pillars',
    title: ['Контент строится вокруг двух-трёх крючков игры', 'Build content around two or three game hooks'],
    summary: [
      'Повторяемые темы делают игру узнаваемой: сильная механика, визуальная фантазия, атмосфера, персонаж или история разработки.',
      'Repeatable themes make the game recognizable: a strong mechanic, visual fantasy, atmosphere, character or development story.',
    ],
    guidance: [
      'Выберите 2–3 крючка и для каждого подготовьте форматы: доказательство геймплеем, закулисье, развлечение и вопрос аудитории. Прямой CTA оставляйте для действительно промо-публикаций.',
      'Choose 2–3 hooks and prepare formats for each: gameplay proof, behind-the-scenes, entertainment and an audience question. Reserve direct CTA for genuinely promotional posts.',
    ],
    tags: ['соцсети', 'контент', 'крючок', 'рубрики', 'social', 'content', 'hooks', 'pillars'],
    pages: '43–45',
    routes: ['/events', '/tasks'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'social-stage-plan',
    title: ['Контент меняется вместе со стадией игры', 'Content changes with the game stage'],
    summary: [
      'Ранний этап создаёт интерес, демо показывает игру и собирает фидбек, предрелиз уточняет обещание, а пострелиз помогает играть и возвращаться.',
      'Early content builds interest, demo content proves and learns, pre-release clarifies the offer, and post-release helps players and brings them back.',
    ],
    guidance: [
      'Для текущей стадии задайте одну цель, 3–4 формата и один CTA. Не публикуйте релизные обещания, когда аудитории ещё нечего увидеть или попробовать.',
      'For the current stage, set one goal, 3–4 formats and one CTA. Do not publish release-style promises when the audience has nothing clear to see or try.',
    ],
    tags: ['контент-план', 'анонс', 'демо', 'релиз', 'content plan', 'announcement', 'demo', 'release'],
    pages: '45–46',
    routes: ['/calendar', '/events'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'social-measurement-loop',
    title: ['Связывайте публикации с результатом в Steam', 'Connect posts to Steam outcomes'],
    summary: [
      'Охват и лайки не равны интересу к игре; важны переходы, конверсия страницы и изменение темпа вишлистов.',
      'Reach and likes are not game interest; visits, page conversion and wishlist velocity matter.',
    ],
    guidance: [
      'Логируйте сильные публикации в журнале, используйте UTM и сравнивайте формат, первый кадр, CTA и аудиторию. Повторяйте не весь пост, а элемент, который поддерживается данными.',
      'Log strong posts, use UTMs and compare format, opening frame, CTA and audience. Repeat the element supported by data, not the entire post blindly.',
    ],
    tags: ['соцсети', 'utm', 'метрики', 'вишлисты', 'social', 'metrics', 'wishlists', 'analytics'],
    pages: '47',
    routes: ['/analytics', '/events'],
    mechanism: 'traffic',
    volatility: 'low',
  }),
  card({
    id: 'social-channel-focus',
    title: ['Меньше каналов, больше нативной работы', 'Use fewer channels more natively'],
    summary: [
      'Один человек редко способен качественно вести много площадок с разными форматами, правилами и ожиданиями аудитории.',
      'One person rarely runs many platforms well when formats, rules and audience expectations differ.',
    ],
    guidance: [
      'Выберите один основной канал для открытия аудитории и один канал удержания. Остальные используйте для адаптированного переиспользования только после устойчивого ритма и измеримого результата.',
      'Choose one primary discovery channel and one retention channel. Reuse adapted content elsewhere only after achieving a sustainable rhythm and measurable result.',
    ],
    tags: ['каналы', 'ресурсы', 'фокус', 'соцсети', 'channels', 'resources', 'focus', 'social'],
    pages: '47–48',
    routes: ['/tasks', '/calendar'],
    mechanism: 'product_workflow',
    volatility: 'medium',
  }),
  card({
    id: 'tiktok-native-test',
    kind: 'heuristic',
    title: ['TikTok тестирует крючок, а не полировку', 'TikTok tests the hook, not polish'],
    summary: [
      'Короткий вертикальный ролик должен сразу показать понятный момент и работать без звука; аутентичность часто важнее рекламного блеска.',
      'A short vertical video should immediately show a clear moment and work without sound; authenticity often beats ad polish.',
    ],
    guidance: [
      'Сделайте 3–5 вариантов одного момента с разными первыми секундами и субтитрами. Публикуйте только реальный контент игры, сравнивайте удержание и CTA, затем усиливайте лучший вариант небольшим тестом.',
      'Create 3–5 versions of one moment with different openings and captions. Publish only genuine game content, compare retention and CTA, then support the best version with a small test.',
    ],
    tags: ['tiktok', 'короткое видео', 'хук', 'субтитры', 'retention', 'vertical video', 'hook'],
    pages: '48–55',
    routes: ['/events', '/analytics'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'reddit-community-first',
    title: [
      'Reddit вознаграждает релевантность, а не маскировку рекламы',
      'Reddit rewards relevance, not disguised ads',
    ],
    summary: [
      'Пост должен быть самостоятельной ценностью для конкретного сабреддита и соответствовать его правилам, даже если ссылку убрать.',
      'A post should provide standalone value to a specific subreddit and follow its rules even if the link is removed.',
    ],
    guidance: [
      'Выберите несколько жанровых сообществ, изучите правила и успешные форматы, публикуйте уникальный devlog, механику или историю и честно обозначайте себя разработчиком. Не используйте накрутку, купленные аккаунты или чужой контент.',
      'Choose a few genre communities, study rules and successful formats, publish an original devlog, mechanic or story, and disclose that you are the developer. Do not use vote manipulation, bought accounts or copied content.',
    ],
    tags: ['reddit', 'сабреддит', 'сообщество', 'devlog', 'subreddit', 'community', 'rules', 'organic'],
    pages: '55–63',
    routes: ['/events', '/tasks'],
    mechanism: 'traffic',
    volatility: 'medium',
  }),
  card({
    id: 'reddit-ads-small-test',
    kind: 'heuristic',
    title: ['Reddit Ads начинайте с узкого теста', 'Start Reddit Ads with a narrow test'],
    summary: [
      'Точный жанровый контекст и естественный креатив обычно важнее широкого охвата.',
      'Precise genre context and a natural creative usually matter more than broad reach.',
    ],
    guidance: [
      'Протестируйте несколько релевантных сообществ и регионов с малым лимитом, отдельными UTM и заранее заданной остановкой по стоимости результата. Не переносите benchmarks между странами и играми без проверки.',
      'Test a few relevant communities and regions with a small cap, separate UTMs and a predefined cost stop. Do not transfer benchmarks between countries and games without validation.',
    ],
    tags: ['reddit ads', 'реклама', 'cpw', 'utm', 'paid', 'ads', 'experiment'],
    pages: '58–63',
    routes: ['/analytics', '/events'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'imgur-visual-story',
    title: ['Imgur нужен визуальный рассказ', 'Imgur needs a visual story'],
    summary: [
      'Прогресс “до/после”, короткая механика или честный смешной баг работают как находка, а не как баннер.',
      'Before/after progress, a short mechanic or an honest funny bug works like a discovery rather than a banner.',
    ],
    guidance: [
      'Соберите один понятный визуальный сюжет, дайте ему самостоятельный заголовок и контекст, а ссылку добавляйте только там, где это уместно. Отслеживайте переходы отдельной UTM.',
      'Build one clear visual story, give it a standalone title and context, and add a link only where appropriate. Track visits with a separate UTM.',
    ],
    tags: ['imgur', 'до после', 'баги', 'визуал', 'before after', 'bugs', 'visual story'],
    pages: '63–66',
    routes: ['/events'],
    mechanism: 'traffic',
    volatility: 'medium',
  }),
  card({
    id: 'x-network-growth',
    kind: 'heuristic',
    title: ['В X маленький аккаунт растёт через сеть', 'A small X account grows through its network'],
    summary: [
      'Без собственной аудитории основную видимость дают полезные ответы, коллаборации, тематические обсуждения и сильные короткие клипы.',
      'Without an owned audience, useful replies, collaborations, topical conversations and strong short clips provide most visibility.',
    ],
    guidance: [
      'Публикуйте короткий понятный геймплей, участвуйте в разговорах по делу и стройте отношения с авторами жанра. Платное продвижение запускайте только на креативе, который уже показал органический интерес.',
      'Publish short, clear gameplay, participate meaningfully in conversations and build relationships with genre creators. Promote only creative that has already shown organic interest.',
    ],
    tags: ['twitter', 'x', 'ответы', 'коллаборации', 'клипы', 'replies', 'network', 'organic'],
    pages: '67–75',
    routes: ['/events', '/creators'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'youtube-evergreen-funnel',
    title: ['YouTube — долгоживущая воронка', 'YouTube is an evergreen funnel'],
    summary: [
      'Трейлер доказывает обещание, devlog строит доверие, gameplay отвечает на интерес, а Shorts приводят к основному контенту.',
      'A trailer proves the promise, devlogs build trust, gameplay answers interest, and Shorts feed long-form content.',
    ],
    guidance: [
      'Разведите форматы по задачам, уберите длинные вступления, сделайте понятную обложку и название, добавьте Steam-ссылку с UTM и улучшайте ролики по CTR и удержанию, а не только просмотрам.',
      'Separate formats by job, remove long intros, create a clear thumbnail and title, add a UTM Steam link, and improve videos using CTR and retention rather than views alone.',
    ],
    tags: ['youtube', 'трейлер', 'devlog', 'shorts', 'ctr', 'retention', 'thumbnail'],
    pages: '76–81',
    routes: ['/events', '/analytics'],
    mechanism: 'traffic',
    volatility: 'medium',
  }),
  card({
    id: 'meta-visual-funnel',
    kind: 'heuristic',
    title: ['Meta-площадки требуют визуальной воронки', 'Meta platforms need a visual funnel'],
    summary: [
      'Reels открывают аудиторию, Stories поддерживают контакт, профиль объясняет игру, а ссылка переводит интерес в Steam.',
      'Reels discover audiences, Stories maintain contact, the profile explains the game, and the link moves interest to Steam.',
    ],
    guidance: [
      'Используйте один вертикальный исходник, но адаптируйте первые секунды, подпись и CTA под площадку. Оформите профиль как краткую страницу игры и измеряйте downstream-переходы отдельно.',
      'Use one vertical source but adapt the opening, caption and CTA per platform. Treat the profile as a concise game page and measure downstream visits separately.',
    ],
    tags: ['instagram', 'facebook', 'reels', 'stories', 'meta', 'профиль', 'vertical video'],
    pages: '81–93',
    routes: ['/events', '/analytics'],
    mechanism: 'traffic',
    volatility: 'high',
    confidence: 'heuristic',
  }),
  card({
    id: 'threads-bluesky-conversation',
    title: ['Threads и BlueSky — разговорные каналы', 'Threads and BlueSky are conversational channels'],
    summary: [
      'Эти площадки полезнее для диалога, наблюдений и связей с творческим сообществом, чем для постоянных прямых продаж.',
      'These platforms are better for dialogue, observations and creative-community relationships than constant direct selling.',
    ],
    guidance: [
      'Публикуйте мысли, процесс и вопросы, отвечайте другим авторам и аккуратно переиспользуйте визуалы из X. Если внутренняя аналитика ограничена, используйте UTM и Steamworks для результата.',
      'Share observations, process and questions, reply to other creators, and carefully reuse visuals from X. When native analytics are limited, rely on UTMs and Steamworks for outcomes.',
    ],
    tags: ['threads', 'bluesky', 'диалог', 'сообщество', 'conversation', 'community', 'utm'],
    pages: '93–98',
    routes: ['/events'],
    mechanism: 'traffic',
    volatility: 'high',
  }),
  card({
    id: 'twitch-micro-creator-plan',
    title: ['На Twitch ищите жанровых микро-стримеров', 'Find genre-fit micro-streamers on Twitch'],
    summary: [
      'Небольшие активные каналы чаще доступны, лучше понимают свою аудиторию и могут дать полезный ранний фидбек.',
      'Smaller active channels are often more accessible, understand their audience well and can provide useful early feedback.',
    ],
    guidance: [
      'Ищите по похожим играм, языку, среднему онлайну и свежести стримов. Связывайтесь через публичный business email или форму, не рекламируйтесь в чате; после стрима сохраняйте клипы и результат.',
      'Search by comparable games, language, average viewers and recency. Use public business email or forms rather than advertising in chat; save clips and outcomes after the stream.',
    ],
    tags: ['twitch', 'стримеры', 'микроинфлюенсеры', 'клипы', 'streamers', 'micro creators', 'clips'],
    pages: '98–101',
    routes: ['/creators', '/events'],
    mechanism: 'outreach',
    volatility: 'medium',
  }),
  card({
    id: 'vk-telegram-owned-audience',
    title: ['VK и Telegram удерживают уже найденную аудиторию', 'VK and Telegram retain an acquired audience'],
    summary: [
      'Канал или сообщество полезны как регулярная точка контакта, но обычно требуют внешнего притока и понятного обещания подписчику.',
      'A channel or community is useful for recurring contact, but usually needs external acquisition and a clear subscriber promise.',
    ],
    guidance: [
      'Оформите профиль, закрепите трейлер и Steam CTA, чередуйте геймплей, devlog, мемы и опросы. Для рекламных размещений проверяйте реальный охват канала и измеряйте переходы отдельной ссылкой.',
      'Complete the profile, pin the trailer and Steam CTA, and rotate gameplay, devlog, memes and polls. For paid placements, verify real channel reach and measure visits with a separate link.',
    ],
    tags: ['vk', 'вконтакте', 'telegram', 'телеграм', 'канал', 'сообщество', 'owned audience', 'community'],
    pages: '101–105',
    routes: ['/events', '/analytics'],
    mechanism: 'traffic',
    volatility: 'high',
  }),
  card({
    id: 'discord-community-operations',
    title: ['Discord — продукт для активного сообщества', 'Discord is a product for an active community'],
    summary: [
      'Сервер не создаёт аудиторию сам: ему нужны внешний приток, понятная структура, регулярные события и модерация.',
      'A server does not create an audience by itself: it needs external acquisition, clear structure, recurring events and moderation.',
    ],
    guidance: [
      'Начните с 5–10 каналов, понятного welcome, ролей для тестеров и мест для фидбека. Назначьте модерацию, проводите AMA или тестовые события и не злоупотребляйте массовыми уведомлениями.',
      'Start with 5–10 channels, a clear welcome, tester roles and feedback spaces. Assign moderation, run AMA or playtest events, and avoid overusing mass notifications.',
    ],
    tags: ['discord', 'комьюнити', 'модерация', 'бета-тест', 'community', 'moderation', 'playtest'],
    pages: '106–109',
    routes: ['/events', '/tasks'],
    mechanism: 'outreach',
    volatility: 'medium',
  }),
  card({
    id: 'dtf-pikabu-editorial',
    title: ['DTF и Пикабу требуют истории, а не пресс-релиза', 'DTF and Pikabu need a story, not a press release'],
    summary: [
      'Полезный разбор разработки, честная история или развлекательный кейс воспринимаются лучше прямой рекламы.',
      'A useful development breakdown, honest story or entertaining case works better than direct advertising.',
    ],
    guidance: [
      'Выберите один конфликт или вывод, подкрепите его визуалами, адаптируйте тон под площадку и закончите вопросом для обсуждения. Ссылку на игру добавляйте прозрачно и без маскировки рекламной цели.',
      'Choose one conflict or lesson, support it with visuals, adapt tone to the platform and end with a discussion question. Add the game link transparently without disguising promotional intent.',
    ],
    tags: ['dtf', 'пикабу', 'статья', 'devlog', 'история', 'editorial', 'story', 'community'],
    pages: '109–112',
    routes: ['/events'],
    mechanism: 'traffic',
    volatility: 'medium',
  }),
  card({
    id: 'case-study-transfer',
    kind: 'case_study',
    title: ['Переносите из кейса механизм, а не цифру', 'Transfer the mechanism, not the number'],
    summary: [
      'Результаты другой игры зависят от жанра, качества, цены, команды, исходной аудитории, календаря и удачи.',
      'Another game’s outcome depends on genre, quality, price, team, starting audience, timing and luck.',
    ],
    guidance: [
      'Разбирая кейс, выпишите контекст, действие, наблюдаемый результат и альтернативные объяснения. Превратите вывод в маленький тест для своей игры, а не в обещание повторить чужой результат.',
      'When reading a case, record context, action, observed outcome and alternative explanations. Turn the lesson into a small test for your game, not a promise to reproduce the result.',
    ],
    tags: ['кейсы', 'статистика', 'гипотеза', 'case study', 'benchmarks', 'hypothesis', 'experiment'],
    pages: '113–125',
    routes: ['/analytics', '/g/'],
    mechanism: 'product_workflow',
    volatility: 'low',
    confidence: 'heuristic',
  }),
]
